### ISSUE TITLE
jetty restart disconnecting from data

### ISSUE THREAD

**Issue by rkhet** [projecthydra/hydra-jetty#34]
Using jettywrapper 1.8.2 and jetty 7.0.0.  Perhaps it's the start.jar, but when I 'rake jetty:stop' then 'rake jetty:start' the solr data appears to be gone no longer shows up in 
SolrAdmin://solr/#/development/query
but appears not to have change on the file system at jetty/solr/development-core/data/index/

It's as if there is some in-memory piece that is lost and it's unable to re-associate with existing data on restart.  Fedora data on disk as well appears to be unchanged but ingest attempts now fail also.  Any thoughts on this?  Might there be some process ID association that persists with the indicies?

**Comment by cam156** [comment]
@rkhet this relates to solr autocommit.  At this point the default solr config does not include auto commit.  See this PR in sufia for the lines to add: https://github.com/projecthydra/sufia/pull/890/files  (and or maybe just copy the entire file?).  I'm not sure this is an issue with jetty as there is the expectation that you will configure jetty for your specific needs.  That said, this might be a sane default, @awead, @jcoyne what do you think?

**Comment by jcoyne** [comment]
If you're using hydra-jetty with Hydra, the expectation is that you will run "rake jetty:config" before "rake jetty:start". This isn't in https://github.com/projecthydra/hydra/wiki/Lesson%3A-install-hydra-jetty, but it should be.

This is fixed in the latest version. See #11

**Comment by acozine** [comment]
I added the rake jetty:config step to the Install Hydra-Jetty instructions.

**Comment by rkhet** [comment]
Thanks all.. the solrconfig.xml addition fixed my dangling data.
