### ISSUE TITLE
Stack trace when running fresh instance of hydra-jetty v8.4.0

### ISSUE THREAD

**Issue by kerchner** [projecthydra/hydra-jetty#36]
I cloned a fresh instance of hydra-jetty, version 8.4.0, and Fedora does not seem to run.

The main page at port 8983 looks good, /solr looks good, but /fedora (and /fedora/rest) yields
```
HTTP ERROR: 503
Problem accessing /fedora. Reason:
    Service Unavailable
```

On the back end, I get the following stack trace on startup: https://gist.github.com/kerchner/e5e4fc78d06e135a5721

I am running Java 1.7.0_79.

When I rolled back to v8.3.1, which uses fcrepo v4.1.1, everything seems to work just fine.

I would also recommend updating the fcrepo/Fedora version referenced in these files:
- https://github.com/projecthydra/hydra-jetty/blob/master/webapps/dashboard/index.html
- https://github.com/projecthydra/hydra-jetty/blob/master/README.md
to match the new version of the WAR file (4.2.0 in this case).

**Comment by jcoyne** [comment]
Are you running Java 8?  Fedora 4.2 requires Java 8.

**Comment by jcoyne** [comment]
Thanks for the recommended updates. Those changes have been made.

**Comment by kerchner** [comment]
@jcoyne I'm running Java 7, as per the README.  I'll give it a try with Java 8.  May want to update the Java dependency mention in the README as well.

**Comment by kerchner** [comment]
@jcoyne - I upgraded to Java 8, and everything works now with Fedora 4.2/hydra-jetty 8.4.0 .  Thanks for your quick response!
